### ISSUE TITLE
More opinionated approach

### ISSUE THREAD

**Issue by gnugat** [ciaranmcnulty/phpspec-typehintedmethods#11]
Hi @ciaranmcnulty, how would you feel about a more opinionated approach? Here's what I'm thinking:

* generate PHPdoc
* if the method is too long (> 120 columns), put each arguments on its own line
* add use statements to avoid FQCN in type hints

The truth is, I've been working on a code generator for a while, but I've been stuck at some point. Finding your phpspec extension and contributing to it just gave me back motivation to continue the project, and I was wondering if I could integrate it here.

The advantage of this approach is that the extension would just be glue code and the actual generation logic can be re used anywhere. The downside is that it totally throws away the "template" feature of phpspec (it is a highly opinionated generator).

What do you think?

**Comment by gnugat** [comment]
I've released v0.3 of the [said library](http://gnugat.github.io/medio/). It currently could replace the argument generation, as you can see [in this example](http://gnugat.github.io/medio/doc/example-phpspec-extension.html).

**Comment by ciaranmcnulty** [comment]
I've discussed this a little with @stof; I think templating, and specifically the ability for extensions to override the templates, is probably important for PhpSpec.

That said if an external library was available for us I'd use it.

**Comment by gnugat** [comment]
Then we'll compose with those restrictions :) .
So the important part here is to be able to:

* generate the arguments (using the placeholder `%arguments%`)
* generate the PHPdoc (no placeholder, but can be located above the line with `%name%`)
* generate the use blocks (no placeholder, but can be located below the namespace declaration)

**Comment by gnugat** [comment]
I'll close this issue and start creating Pull request :)
