### ISSUE TITLE
Cannot get version 1.1.0

### ISSUE THREAD

**Issue by gnugat** [ciaranmcnulty/phpspec-typehintedmethods#12]
Hello,

It looks like a tag has been misspelled (v1.01), and somehow composer thinks it is a higher version than v1.1.0.
Would it be possible to rename the tag and update packagist?

**Comment by ciaranmcnulty** [comment]
Try now?

**Comment by gnugat** [comment]
I've tried the following:

```
rm -rf ~/.composer # Removing composer cache
rm -rf /tmp/meh
mkdir /tmp/meh
cd /tmp/meh
composer require ciaranmcnulty/phpspec-typehintedmethods:1.1.0
```

Then: `composer show -i ciaranmcnulty/phpspec-typehintedmethods | grep versions` prints: `versions : * 1.01`.

I guess you need to manually remove this version from packagist.

**Comment by gnugat** [comment]
By the way you can rename a tag using:

```
git tag v1.01 v1.0.1
git -d v1.01
```

Basically it creates a new tag from the old one, and then you can remove the old one

**Comment by ciaranmcnulty** [comment]
I renamed the tag in github through the UI.

It looks like it was still listed on packagist; I've deleted it manually through packagist too. 

Try again later when there's some time for any caching to expire.

**Comment by gnugat** [comment]
Looks good now, thanks!

**Comment by jdreesen** [comment]
Seems like `v1.01` tag slipped back in somehow. I'm not able to install `v1.1.0` through composer at the moment :(

**Comment by gnugat** [comment]
Looks like this tag is back on packagist, it needs to be first removed from git:

```
git tag -d v1.01
git push origin :refs/tags/v1.01
```

And then from packagist.

**Comment by ciaranmcnulty** [comment]
That's... very odd. I've not touched this repository in a long time.

**Comment by gnugat** [comment]
Maybe packagist runs automatic checks from time to time?

**Comment by ciaranmcnulty** [comment]
OK `1.01` is deleted locally, the tag is pushed to github, and it appears to be gone from packagist, and when I specify `~1.0` in composer I get `1.1.0`

**Comment by gnugat** [comment]
@jdreesen: Is it fixed for you?

**Comment by jdreesen** [comment]
Yes, now it tries to install `1.1.0`... and then fails because I use PhpSpec `2.3.0`. Is there a specific reason that this only supports `<=2.2`?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ciaranmcnulty/phpspec-typehintedmethods ^1.1 -> satisfiable by ciaranmcnulty/phpspec-typehintedmethods[1.1.0].
    - ciaranmcnulty/phpspec-typehintedmethods 1.1.0 requires phpspec/phpspec ~2.0,<=2.2 -> no matching package found.
```

**Comment by ciaranmcnulty** [comment]
PhpSpec's SemVer doesn't guarantee extension compatibility, yet

**Comment by jdreesen** [comment]
I understand, thx. I think this can be closed now.

**Comment by gnugat** [comment]
@jdreesen the extension now supports phpspec 2.3 and 2.4 ;)
